### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by olafur-palsson** [terkelg/prompts#403]
### Is your feature request related to a problem?
This is something odd I noticed. It looks like in general prompts works except when you run two question sequentially.

```js
// index.js
const prompts = require('prompts')
// Works just fine
const response1 = await prompts({
  type: 'text',
  name: 'msg',
  message: 'Question'
})

// Not possible to use inputs anymore
const response2 = await prompts({
  type: 'text',
  name: 'msg',
  message: 'Question'
})

```

### Describe the solution you'd like
It works when running with bun like when running with node.

### Describe alternatives you've considered
Using node lol.

### Additional context
None

**Comment by ericklarsen** [comment]
it happened on my side too.

**Comment by sonyarianto** [comment]
true true just run `bun run example.js` on this repo and on second question my WSL is hang :)

**Comment by sonyarianto** [comment]
refer to this https://github.com/oven-sh/bun/issues/4664

**Comment by olafur-palsson** [comment]
I took a look around and a lot of cli libraries are having issues.
https://github.com/oven-sh/bun/issues/4787
https://github.com/oven-sh/bun/issues/5267

But here's one that says it's fixed in the upcoming bun release (@clack/prompts on npm)
https://github.com/natemoo-re/clack/issues/159

**Comment by sonyarianto** [comment]
@olafur-palsson Hi, for me Bun with @clack/prompts is no problem, but with terkelg/prompts has the issue CMIIW.

In @clack/prompts to test is easy, just clone that repo, and run `bun --bun run examples/basic/index.ts` it run smooth :)

**Comment by olafur-palsson** [comment]
@sonyarianto 
They have issue with these. There's some weird behavior when closing the `readline` interface in Bun I think.

Try running this one:
```
import * as p from '@clack/prompts';

await p.text({
  message: 'Where should we create your project?',
  placeholder: './lol',
})

await p.text({
  message: 'Where should we create your project?',
  placeholder: './lol',
})
```

**Comment by sonyarianto** [comment]
Hmmm with Bun 1.0.2 above script also still not working properly.

**Comment by sonyarianto** [comment]
@olafur-palsson butttt if you modify the code like this, inside the async then it will work smoothly.

```js
import * as p from '@clack/prompts';

async function main() {
  const response1 = await p.text({
    message: 'Where should we create your project?',
    placeholder: './lol',
  });

  const response2 = await p.text({
    message: 'Where should we create your project?',
    placeholder: './lol',
  });
}

await main();
```

**Comment by jhormanrus** [comment]
This issue has already been addressed in the latest release of Bun, v1.0.18. You can find more details about the fix in the release notes: [Bun v1.0.18 Release Notes](https://bun.sh/blog/bun-v1.0.18#fixed-hang-when-reading-from-process-stdin).

**Comment by michaelhays** [comment]
Confirmed that this is no longer an issue with Bun v1.0.18, so this issue can probably be closed.

**Comment by davidgomes** [comment]
This can still happen on Bun, even after their v1.0.18 version.

Here's a repro/bug on Bun's issue tracker: https://github.com/oven-sh/bun/issues/9855#issuecomment-2224861121
